name: Build

on:
    push:
        branches:
            - master

env:
    AZURE_WEBAPP_NAME: news-reader
    AZURE_WEBAPP_PACKAGE_PATH: "./api"
    NODE_VERSION: "12.x"

jobs:
    build-and-deploy:
        name: Build and Deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Use Node.js ${{ env.NODE_VERSION }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ env.NODE_VERSION }}
            - name: install and build
              run: |
                  make build
            - name: Deploy to Azure
              uses: azure/webapps-deploy@v1
              with:
                  app-name: ${{ env.AZURE_WEBAPP_NAME }}
                  publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
                  package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
